# -*- coding: utf-8 -*-
"""trocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLpcX0uqIpNqkW7zcUmXtd_Pr9JZEo5P
"""

!which python
!python --version

!echo $PYTHONPATH

# Commented out IPython magic to ensure Python compatibility.
# %env PYTHONPATH=

!echo $PYTHONPATH

# Commented out IPython magic to ensure Python compatibility.
# %env PYTHONPATH=
! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.12.0-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.12.0-Linux-x86_64.sh -b -f -p /content/miniconda3

# Commented out IPython magic to ensure Python compatibility.
import os
path = '/content/miniconda3/bin:' + os.environ['PATH']
# %env PATH=$path

!conda install --channel defaults conda python=3.9.16 --yes
!conda update --channel defaults --all --yes

!which conda
!conda --version

! conda --version

# Commented out IPython magic to ensure Python compatibility.
# %pwd       

cd drive/MyDrive/trocr

! conda env create -n trocr_env --file environment.yml

! activate trocr_env

!pip freeze

# Commented out IPython magic to ensure Python compatibility.
# %pwd

! python -m pip install Pillow

! python -m pip install torch

! python -m pip install transformers

! python -m pip install typer

#! python -m src predict train/TRAIN_00001.jpg train/TRAIN_00002.jpg

! python -m src train --local-model

! python -m src predict train/TRAIN_00001.jpg train/TRAIN_00002.jpg

